AOMediaCodec/av1-isobmff

index.bs
index.html

Related to #4 
- Provide procedure to check conformance
- Provide guidance if too difficult to set

rewrite the initial_presentation_delay semantics

---

index.bs
index.html

Corresponds to https://github.com/AOMediaCodec/av1-spec/commit/9413145907b61d28b6ebe0b6acfd58e090288ab4
in AV1 spec.
Addresses https://github.com/AOMediaCodec/av1-isobmff/issues/20

Update level related info to refer to seq_level_idx.

---

index.bs
index.html

remove still_picture from codecs

---

index.bs
index.html

@Cyril: FYI; this is just s/bistream/bitstream/

Fix a couple of typos: bistream -> bitstream.

---

biblio.json
index.bs
index.html

@cconcolato: One last FYI PR. This one updates the date and fixes the spec link within biblio.json.

Fix AV1 spec link in biblio.json and update date.

---

index.bs
index.html

simplification of the CMAF section

---

index.bs
index.html

Fix default chroma sample location in codecs parameter

---

index.bs
index.html

clarify use of ISOMBFF brands 

---

index.bs
index.html

Addresses https://github.com/AOMediaCodec/av1-isobmff/commit/fc87601a11f7adf109d109f067b488f9f5abd77e#commitcomment-30056786

clarify chroma subsampling value in example 

---

index.bs
index.html

Indicate explicitly that Tile List OBUs are not supported 

---

index.bs
index.html

For review during Sept 4th conf call as a possible option.
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/116.html" title="Last updated on Aug 30, 2019, 4:11 PM UTC (1cdf69d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/116/8a2e4cf...1cdf69d.html" title="Last updated on Aug 30, 2019, 4:11 PM UTC (1cdf69d)">Diff</a>

changing cbcs alignment

---

README.md
index.bs
v1.0.0.html
v1.1.0.html

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/132.html" title="Last updated on Oct 19, 2021, 9:27 PM UTC (0a7160f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/132/ee2f1f0...0a7160f.html" title="Last updated on Oct 19, 2021, 9:27 PM UTC (0a7160f)">Diff</a>

Bikeshed update

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/podborski/av1-isobmff/pull/139.html" title="Last updated on Feb 7, 2022, 5:20 PM UTC (83e2dcc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/139/6bbc83c...podborski:83e2dcc.html" title="Last updated on Feb 7, 2022, 5:20 PM UTC (83e2dcc)">Diff</a>

Minor fixes

---

index.bs

close #149
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/152.html" title="Last updated on Oct 3, 2022, 8:13 PM UTC (0724120)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/152/60a6eb1...0724120.html" title="Last updated on Oct 3, 2022, 8:13 PM UTC (0724120)">Diff</a>

remove clap restriction

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-isobmff/pull/154.html" title="Last updated on Oct 10, 2022, 10:58 PM UTC (4933f11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/154/12a27a7...wantehchang:4933f11.html" title="Last updated on Oct 10, 2022, 10:58 PM UTC (4933f11)">Diff</a>

Use list items in the changelist section

---

index.bs

close #157
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/162.html" title="Last updated on Nov 29, 2022, 7:02 PM UTC (0def984)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/162/acf8095...0def984.html" title="Last updated on Nov 29, 2022, 7:02 PM UTC (0def984)">Diff</a>

clarify that encryption changes the sample entry type

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/190.html" title="Last updated on Dec 11, 2023, 7:23 PM UTC (88e35d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/190/2fd9e08...88e35d0.html" title="Last updated on Dec 11, 2023, 7:23 PM UTC (88e35d0)">Diff</a>

align draft header with previous

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/191.html" title="Last updated on Dec 11, 2023, 7:28 PM UTC (da10f07)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/191/2fd9e08...da10f07.html" title="Last updated on Dec 11, 2023, 7:28 PM UTC (da10f07)">Diff</a>

remove former author

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/192.html" title="Last updated on Dec 11, 2023, 7:30 PM UTC (d7bf933)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/192/2fd9e08...d7bf933.html" title="Last updated on Dec 11, 2023, 7:30 PM UTC (d7bf933)">Diff</a>

update date to today

---

conformance/conformance_page/src/App.jsx
index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/198.html" title="Last updated on Mar 4, 2024, 8:10 PM UTC (91ddf1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/198/4d8cbfe...91ddf1b.html" title="Last updated on Mar 4, 2024, 8:10 PM UTC (91ddf1b)">Diff</a>

add a link to the conformance page and a script for section highlighting

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/200.html" title="Last updated on Mar 5, 2024, 10:03 AM UTC (ca53c69)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/200/824cf4e...ca53c69.html" title="Last updated on Mar 5, 2024, 10:03 AM UTC (ca53c69)">Diff</a>

add missing close assert
