- index.bs
- index.html
Related to #9 
- add still_picture field
- clarify that first operating point is used
- add support for extensibility if we want to add other operating points.
> update codecs parameter to latest spec

- index.bs
- index.html
Fixes to address problems reported by Alexis Tourapis (Apple):
> Since in your example you use PQ as the transfer characteristics, it might be better when you mention the values for color primaries and matrix coefficients to quote BT.2100 and not BT.2020. They are the same of course, but it would seem better to quote the right spec. It is also somewhat odd that you used a level 1 example. Maybe specifying level 4 could be more realistic? I would also suggest using the narrow/studio range in your example since that is much more common for this example usage. Btw, it seems you also used profile 2. Wouldn’t this configuration fit in profile 0? If you check the spec, for profile 2 and for 10 bit data, only 4:2:2 is implicitly permitted. You also seem to have an issue when the colour …
> Further fixes to the codecs parameter 

- index.bs
- index.html
Following the discussions in the RTC group as reported in #10, this PR replaces #10, removes the OBU_length_mode and closes #3.
> remove OBU_length_mode

- index.bs
- index.html
A couple small changes:
1) initial_display_delay_minus_1 in the latest buffer model proposal is 4 bits.
I've updated the field in the sample entry to use 4 bits.
2) Add initial_presentation_delay_present flag.
> Initial presentation delay updates.

- index.bs
- index.html
This PR allows 'bikeshed spec' to complete without error, and removes
the requirement that we include -f in the command line when running
bikeshed.
- Change pre class to def for definitions.
- Fix propdesc error for 'av01'.
- Fix fatal errors related to anchors.
- Fix av1configurationbox link error.
- Fix av1codecconfigurationrecord link error.
- Add missing anchors.
- Silence unexported dfn warnings.
- Render index.html from index.bs with fixes included.
Fixes https://github.com/AOMediaCodec/av1-isobmff/issues/27
> Fix bikeshed errors

- index.bs
- index.html
Closes #18 
Similarly, I think we should also replace the still boolean by a letter 'V' for video profiles and 'S' for Still picture profiles. That would make the codecs more readable.
> adding tier in codecs parameter

- index.bs
- index.html
@cconcolato: FYI again; fixed the links. AV1 spec is now hosted on github.io.
> AV1 spec PDF moved. Update links.

- index.bs
- index.html
Some of the terms used are confusing because they don't match what the AV1 spec uses. Here are 2 patch that address obvious ones.
Addresses #49
> Update vocabulary to match AV1 1.0.0 specification

- index.bs
- index.html
- remaining -> remainder in bullet for omitted OBU size fields.
- switchframeamplegroupentry -> switchframesamplegroupentry
- add a couple missing commas
> Minor punctuation and typo fixes.

- index.bs
- index.html
- Use the word 'protected' instead of 'encrypted' to match CENC
- make it clear that subsample encryption is required in protected samples and clarify difference in protection scheme following CENC
- clarify the association between subsample and OBU
- clarify what part of protected OBU can be protected
> Further clarify the encryption section

- biblio.json
- index.bs
- index.html
Add the following fields to AV1CodecConfigurationRecord:
- version  
- seq_profile
- still_picture
- seq_level_idx_0
- seq_tier_0
- bit_depth
- monochrome
- chroma_subsampling_x
- chroma_subsampling_y
- chrome_sample_position
Also, some minor tweaks:
- Update date.
- Update AV1 bitstream spec status (LS -> Standard).
- Add seq_profile, still_picture, mono_chrome to
subsampling_x, subsampling_y, and 
chroma_sample_position to terms defined in AV1.
> Add more Sequence Header OBU parameters to AV1CodecConfigurationRecord.

- index.bs
- index.html
The most recent pull request (PR57) was merged without regenerating the
bikeshed output. This commit regerates the output, and also removes
an extra space.
> Fix stale bikeshed output.

- index.bs
- index.html
Make the presence of seq_profile in AV1CodecConfigurationRecordv1
mandatory, and add marker bit to avoid producing config
records that share bit patterns similar to OBU headers.
> Mandatory seq_profile and add marker bit.

- index.bs
- index.html
- still_picture, seq_level_idx_0, and seq_tier_0 are required.
- s/sequence_parameters_present/color_parameters_present/
- swap monochrome and bit_depth in the color parameters to
keep all the bits for bit_depth in the same byte.
issue: https://github.com/AOMediaCodec/av1-isobmff/issues/50
> Make still picture, level, and tier mandatory in av1C.

- index.bs
- index.html
> Do not force creation of a subsegment for tiles too small to be encrypted

- index.bs
- index.html
This PR addresses a comment made in #109. This is an initial proposal to recommend the use of 1+9 over other patterns.
> add recommendation to use the 1+9 pattern

- index.bs
The changelist section "Changes since v1.1.0 release" is renamed
"Changes since v1.2.0 release".
Fix https://github.com/AOMediaCodec/av1-isobmff/issues/143.
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-isobmff/pull/144.html" title="Last updated on May 2, 2022, 4:28 PM UTC (11d4363)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/144/be8adcc...wantehchang:11d4363.html" title="Last updated on May 2, 2022, 4:28 PM UTC (11d4363)">Diff</a>
> Rename the changelist section for the next version

- index.bs
Use two digits for the default values of colorPrimaries, transferCharacteristics, and matrixCoefficients.
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-isobmff/pull/155.html" title="Last updated on Oct 11, 2022, 12:04 AM UTC (94bcbcc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/155/12a27a7...wantehchang:94bcbcc.html" title="Last updated on Oct 11, 2022, 12:04 AM UTC (94bcbcc)">Diff</a>
> Use two digits for CP, TC, and MC default values

- v1.0.0.html
- v1.1.0.html
- v1.2.0.html
close #160 
If approved, we still need to copy the HTML files for the old versions to the gh-pages branch, as currently the publication tools only publish the main `index.html` file.
> Fix version headers in main branch

- index.bs
Fix https://github.com/AOMediaCodec/av1-isobmff/issues/126.
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-isobmff/pull/167.html" title="Last updated on Apr 7, 2023, 10:36 PM UTC (397984b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/167/c870786...wantehchang:397984b.html" title="Last updated on Apr 7, 2023, 10:36 PM UTC (397984b)">Diff</a>
> Clarify the `colr` box

- index.bs
The single quotes inside a `<a href></a>` element are still treated as an autolink to a CSS property and terminate the link specified in the `<a>` element. Remove all single quotes from the changelist section.
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-isobmff/pull/173.html" title="Last updated on Jun 12, 2023, 7:16 PM UTC (a544b01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/173/e95f6e0...wantehchang:a544b01.html" title="Last updated on Jun 12, 2023, 7:16 PM UTC (a544b01)">Diff</a>
> Remove single quotes from the changelist section

- index.bs
newline before `extends` keyword,
newline before opening `{`
syntax highlight for cpp
remove unnecessary spaces
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/175.html" title="Last updated on Sep 18, 2023, 5:09 PM UTC (6dbceaa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/175/2754170...6dbceaa.html" title="Last updated on Sep 18, 2023, 5:09 PM UTC (6dbceaa)">Diff</a>
> address #163

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/170.html" title="Last updated on Sep 18, 2023, 4:18 PM UTC (2f7871a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/170/2754170...2f7871a.html" title="Last updated on Sep 18, 2023, 4:18 PM UTC (2f7871a)">Diff</a>
> align with current CMAF version mentioing cmf2 brand

- index.bs
Fix https://github.com/AOMediaCodec/av1-isobmff/issues/135
***
<a href="https://pr-preview.s3.amazonaws.com/wantehchang/av1-isobmff/pull/174.html" title="Last updated on Sep 22, 2023, 4:05 PM UTC (8d3ecf6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/174/5c92d62...wantehchang:8d3ecf6.html" title="Last updated on Sep 22, 2023, 4:05 PM UTC (8d3ecf6)">Diff</a>
> Correct the page numbers in links to the AV1 spec

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/183.html" title="Last updated on Nov 29, 2023, 3:03 AM UTC (4475db2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/183/014d8ea...4475db2.html" title="Last updated on Nov 29, 2023, 3:03 AM UTC (4475db2)">Diff</a>
> Use undated reference for ISOBMFF

- .github/workflows/auto-publish.yml
- .github/workflows/check-pr.yml
- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/196.html" title="Last updated on Feb 22, 2024, 1:49 AM UTC (bcf9ca5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/196/dc1c8c0...bcf9ca5.html" title="Last updated on Feb 22, 2024, 1:49 AM UTC (bcf9ca5)">Diff</a>
> update editor list

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/195.html" title="Last updated on Mar 4, 2024, 6:21 PM UTC (41897d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/195/dc1c8c0...41897d5.html" title="Last updated on Mar 4, 2024, 6:21 PM UTC (41897d5)">Diff</a>
> add note for encryption description limit

- index.bs
To be merged after formal approval from the WG
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/pull/199.html" title="Last updated on Mar 4, 2024, 11:22 PM UTC (f6a5cc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-isobmff/199/824cf4e...f6a5cc0.html" title="Last updated on Mar 4, 2024, 11:22 PM UTC (f6a5cc0)">Diff</a>
> Update document status to WG approved
